# Generated by Django 4.2.3 on 2023-08-11 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('status', models.SmallIntegerField(choices=[('1', 'active'), ('2', 'inactive'), ('3', 'sold')], default='1')),
                ('is_archive', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField()),
                ('is_agent', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=5, max_digits=50)),
                ('negotiable', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('seller_name', models.CharField(max_length=30)),
                ('contact_email', models.EmailField(max_length=50)),
                ('contact_phone', models.CharField(max_length=13)),
                ('purchased_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': '-updated_at',
                'abstract': False,
            },
        ),
    ]
