# Generated by Django 4.2.3 on 2023-08-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_feed', '0003_alter_advertisement_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='purchased_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
