# Generated by Django 4.2.3 on 2023-08-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_feed', '0005_alter_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'inactive'), (3, 'sold')], default=1),
        ),
    ]
